### PR TITLE
Zoom SDK version migration

### PR DESCRIPTION
**Pull request by suhailzoft**

### CODE REVIEW

**Comment by suhailzoft** [comment]
This PR does n't contain code for create meeting feature. So, I'm closing it now. Let me know if someone wants to reopen it.

**Comment by moazelsawaf** [comment]
Yes open it again please, it is very useful since the package maintenance almost stopped.

**Comment by moazelsawaf** [comment]
I have an issue while building IOS which says:

```
- Installing target `flutter_zoom_sdk` iOS 9.0
 [!] Unable to install vendored xcframework `MobileRTC` for Pod `flutter_zoom_sdk`, because it contains both static and dynamic frameworks.

```

Can you help me on that please?

**Comment by suhailzoft** [comment]
@moazelsawaf Use the main branch instead of master.

**Comment by suhailzoft** [comment]
I'm not promoting this because the user can't create any meetings. Additional effort is needed to do so and I don't have that much time to sit on it.  Don't use it if you're planning to do so.

**Comment by moazelsawaf** [comment]
Thanks it worked ❤

Also I just want to use the package to join a meeting, so it suits my requirements very well.

**Pull request closed without merging**
